/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleFinderRouteImport } from './routes/vehicle-finder'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as PartnerOrdersRouteImport } from './routes/partner.orders'
import { Route as PartnerEngineersRouteImport } from './routes/partner.engineers'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminManufacturersRouteImport } from './routes/admin.manufacturers'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminFuelsRouteImport } from './routes/admin.fuels'
import { Route as AdminDeliveryTimeRouteImport } from './routes/admin.delivery-time'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCapacitiesRouteImport } from './routes/admin.capacities'
import { Route as AdminCallbacksRouteImport } from './routes/admin.callbacks'
import { Route as AdminBulkPricingRouteImport } from './routes/admin.bulk-pricing'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminPartnersIndexRouteImport } from './routes/admin.partners.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminEngineersIndexRouteImport } from './routes/admin.engineers.index'
import { Route as ManufacturersCategorySlugMakeSlugRouteImport } from './routes/manufacturers.$categorySlug.$makeSlug'
import { Route as AdminSeoPagesRouteImport } from './routes/admin.seo.pages'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminPartnersNewRouteImport } from './routes/admin.partners.new'
import { Route as AdminPagesNewRouteImport } from './routes/admin.pages.new'
import { Route as AdminOrdersCreateRouteImport } from './routes/admin.orders.create'
import { Route as AdminEngineersNewRouteImport } from './routes/admin.engineers.new'
import { Route as AdminSeoQuickProductsRouteImport } from './routes/admin.seo.quick.products'
import { Route as AdminSeoQuickManufacturersRouteImport } from './routes/admin.seo.quick.manufacturers'
import { Route as AdminSeoQuickCategoriesRouteImport } from './routes/admin.seo.quick.categories'
import { Route as AdminSeoQuickBrandsRouteImport } from './routes/admin.seo.quick.brands'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin.products.$productId.edit'
import { Route as AdminPagesPageIdEditRouteImport } from './routes/admin.pages.$pageId.edit'

const VehicleFinderRoute = VehicleFinderRouteImport.update({
  id: '/vehicle-finder',
  path: '/vehicle-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOrdersRoute = PartnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerEngineersRoute = PartnerEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => PartnerRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManufacturersRoute = AdminManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuelsRoute = AdminFuelsRouteImport.update({
  id: '/fuels',
  path: '/fuels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryTimeRoute = AdminDeliveryTimeRouteImport.update({
  id: '/delivery-time',
  path: '/delivery-time',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapacitiesRoute = AdminCapacitiesRouteImport.update({
  id: '/capacities',
  path: '/capacities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbacksRoute = AdminCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkPricingRoute = AdminBulkPricingRouteImport.update({
  id: '/bulk-pricing',
  path: '/bulk-pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersIndexRoute = AdminPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngineersIndexRoute = AdminEngineersIndexRouteImport.update({
  id: '/engineers/',
  path: '/engineers/',
  getParentRoute: () => AdminRoute,
} as any)
const ManufacturersCategorySlugMakeSlugRoute =
  ManufacturersCategorySlugMakeSlugRouteImport.update({
    id: '/manufacturers/$categorySlug/$makeSlug',
    path: '/manufacturers/$categorySlug/$makeSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSeoPagesRoute = AdminSeoPagesRouteImport.update({
  id: '/seo/pages',
  path: '/seo/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersNewRoute = AdminPartnersNewRouteImport.update({
  id: '/partners/new',
  path: '/partners/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersCreateRoute = AdminOrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngineersNewRoute = AdminEngineersNewRouteImport.update({
  id: '/engineers/new',
  path: '/engineers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoQuickProductsRoute = AdminSeoQuickProductsRouteImport.update({
  id: '/seo/quick/products',
  path: '/seo/quick/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoQuickManufacturersRoute =
  AdminSeoQuickManufacturersRouteImport.update({
    id: '/seo/quick/manufacturers',
    path: '/seo/quick/manufacturers',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSeoQuickCategoriesRoute = AdminSeoQuickCategoriesRouteImport.update({
  id: '/seo/quick/categories',
  path: '/seo/quick/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoQuickBrandsRoute = AdminSeoQuickBrandsRouteImport.update({
  id: '/seo/quick/brands',
  path: '/seo/quick/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPagesPageIdEditRoute = AdminPagesPageIdEditRouteImport.update({
  id: '/pages/$pageId/edit',
  path: '/pages/$pageId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/partner': typeof PartnerRouteWithChildren
  '/vehicle-finder': typeof VehicleFinderRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/bulk-pricing': typeof AdminBulkPricingRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/capacities': typeof AdminCapacitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-time': typeof AdminDeliveryTimeRoute
  '/admin/fuels': typeof AdminFuelsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/partner/engineers': typeof PartnerEngineersRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/engineers/new': typeof AdminEngineersNewRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/seo/pages': typeof AdminSeoPagesRoute
  '/manufacturers/$categorySlug/$makeSlug': typeof ManufacturersCategorySlugMakeSlugRoute
  '/admin/engineers/': typeof AdminEngineersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/seo/quick/brands': typeof AdminSeoQuickBrandsRoute
  '/admin/seo/quick/categories': typeof AdminSeoQuickCategoriesRoute
  '/admin/seo/quick/manufacturers': typeof AdminSeoQuickManufacturersRoute
  '/admin/seo/quick/products': typeof AdminSeoQuickProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/vehicle-finder': typeof VehicleFinderRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/bulk-pricing': typeof AdminBulkPricingRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/capacities': typeof AdminCapacitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-time': typeof AdminDeliveryTimeRoute
  '/admin/fuels': typeof AdminFuelsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/partner/engineers': typeof PartnerEngineersRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/engineers/new': typeof AdminEngineersNewRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/seo/pages': typeof AdminSeoPagesRoute
  '/manufacturers/$categorySlug/$makeSlug': typeof ManufacturersCategorySlugMakeSlugRoute
  '/admin/engineers': typeof AdminEngineersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/partners': typeof AdminPartnersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/seo/quick/brands': typeof AdminSeoQuickBrandsRoute
  '/admin/seo/quick/categories': typeof AdminSeoQuickCategoriesRoute
  '/admin/seo/quick/manufacturers': typeof AdminSeoQuickManufacturersRoute
  '/admin/seo/quick/products': typeof AdminSeoQuickProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/partner': typeof PartnerRouteWithChildren
  '/vehicle-finder': typeof VehicleFinderRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/bulk-pricing': typeof AdminBulkPricingRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/capacities': typeof AdminCapacitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-time': typeof AdminDeliveryTimeRoute
  '/admin/fuels': typeof AdminFuelsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/partner/engineers': typeof PartnerEngineersRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/engineers/new': typeof AdminEngineersNewRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/seo/pages': typeof AdminSeoPagesRoute
  '/manufacturers/$categorySlug/$makeSlug': typeof ManufacturersCategorySlugMakeSlugRoute
  '/admin/engineers/': typeof AdminEngineersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/seo/quick/brands': typeof AdminSeoQuickBrandsRoute
  '/admin/seo/quick/categories': typeof AdminSeoQuickCategoriesRoute
  '/admin/seo/quick/manufacturers': typeof AdminSeoQuickManufacturersRoute
  '/admin/seo/quick/products': typeof AdminSeoQuickProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/partner'
    | '/vehicle-finder'
    | '/login'
    | '/register'
    | '/admin/banners'
    | '/admin/brands'
    | '/admin/bulk-pricing'
    | '/admin/callbacks'
    | '/admin/capacities'
    | '/admin/categories'
    | '/admin/delivery-time'
    | '/admin/fuels'
    | '/admin/locations'
    | '/admin/manufacturers'
    | '/admin/users'
    | '/admin/vehicles'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/partner/engineers'
    | '/partner/orders'
    | '/products/$id'
    | '/admin/'
    | '/orders/'
    | '/partner/'
    | '/products/'
    | '/admin/engineers/new'
    | '/admin/orders/create'
    | '/admin/pages/new'
    | '/admin/partners/new'
    | '/admin/products/new'
    | '/admin/seo/pages'
    | '/manufacturers/$categorySlug/$makeSlug'
    | '/admin/engineers/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/admin/products/'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/seo/quick/brands'
    | '/admin/seo/quick/categories'
    | '/admin/seo/quick/manufacturers'
    | '/admin/seo/quick/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/vehicle-finder'
    | '/login'
    | '/register'
    | '/admin/banners'
    | '/admin/brands'
    | '/admin/bulk-pricing'
    | '/admin/callbacks'
    | '/admin/capacities'
    | '/admin/categories'
    | '/admin/delivery-time'
    | '/admin/fuels'
    | '/admin/locations'
    | '/admin/manufacturers'
    | '/admin/users'
    | '/admin/vehicles'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/partner/engineers'
    | '/partner/orders'
    | '/products/$id'
    | '/admin'
    | '/orders'
    | '/partner'
    | '/products'
    | '/admin/engineers/new'
    | '/admin/orders/create'
    | '/admin/pages/new'
    | '/admin/partners/new'
    | '/admin/products/new'
    | '/admin/seo/pages'
    | '/manufacturers/$categorySlug/$makeSlug'
    | '/admin/engineers'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/seo/quick/brands'
    | '/admin/seo/quick/categories'
    | '/admin/seo/quick/manufacturers'
    | '/admin/seo/quick/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/partner'
    | '/vehicle-finder'
    | '/_auth/login'
    | '/_auth/register'
    | '/admin/banners'
    | '/admin/brands'
    | '/admin/bulk-pricing'
    | '/admin/callbacks'
    | '/admin/capacities'
    | '/admin/categories'
    | '/admin/delivery-time'
    | '/admin/fuels'
    | '/admin/locations'
    | '/admin/manufacturers'
    | '/admin/users'
    | '/admin/vehicles'
    | '/orders/$orderId'
    | '/p/$slug'
    | '/partner/engineers'
    | '/partner/orders'
    | '/products/$id'
    | '/admin/'
    | '/orders/'
    | '/partner/'
    | '/products/'
    | '/admin/engineers/new'
    | '/admin/orders/create'
    | '/admin/pages/new'
    | '/admin/partners/new'
    | '/admin/products/new'
    | '/admin/seo/pages'
    | '/manufacturers/$categorySlug/$makeSlug'
    | '/admin/engineers/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/admin/products/'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/seo/quick/brands'
    | '/admin/seo/quick/categories'
    | '/admin/seo/quick/manufacturers'
    | '/admin/seo/quick/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  VehicleFinderRoute: typeof VehicleFinderRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PSlugRoute: typeof PSlugRoute
  ProductsIdRoute: typeof ProductsIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ManufacturersCategorySlugMakeSlugRoute: typeof ManufacturersCategorySlugMakeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-finder': {
      id: '/vehicle-finder'
      path: '/vehicle-finder'
      fullPath: '/vehicle-finder'
      preLoaderRoute: typeof VehicleFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/orders': {
      id: '/partner/orders'
      path: '/orders'
      fullPath: '/partner/orders'
      preLoaderRoute: typeof PartnerOrdersRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/engineers': {
      id: '/partner/engineers'
      path: '/engineers'
      fullPath: '/partner/engineers'
      preLoaderRoute: typeof PartnerEngineersRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manufacturers': {
      id: '/admin/manufacturers'
      path: '/manufacturers'
      fullPath: '/admin/manufacturers'
      preLoaderRoute: typeof AdminManufacturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fuels': {
      id: '/admin/fuels'
      path: '/fuels'
      fullPath: '/admin/fuels'
      preLoaderRoute: typeof AdminFuelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery-time': {
      id: '/admin/delivery-time'
      path: '/delivery-time'
      fullPath: '/admin/delivery-time'
      preLoaderRoute: typeof AdminDeliveryTimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capacities': {
      id: '/admin/capacities'
      path: '/capacities'
      fullPath: '/admin/capacities'
      preLoaderRoute: typeof AdminCapacitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callbacks': {
      id: '/admin/callbacks'
      path: '/callbacks'
      fullPath: '/admin/callbacks'
      preLoaderRoute: typeof AdminCallbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-pricing': {
      id: '/admin/bulk-pricing'
      path: '/bulk-pricing'
      fullPath: '/admin/bulk-pricing'
      preLoaderRoute: typeof AdminBulkPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners/': {
      id: '/admin/partners/'
      path: '/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AdminPartnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engineers/': {
      id: '/admin/engineers/'
      path: '/engineers'
      fullPath: '/admin/engineers/'
      preLoaderRoute: typeof AdminEngineersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manufacturers/$categorySlug/$makeSlug': {
      id: '/manufacturers/$categorySlug/$makeSlug'
      path: '/manufacturers/$categorySlug/$makeSlug'
      fullPath: '/manufacturers/$categorySlug/$makeSlug'
      preLoaderRoute: typeof ManufacturersCategorySlugMakeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/pages': {
      id: '/admin/seo/pages'
      path: '/seo/pages'
      fullPath: '/admin/seo/pages'
      preLoaderRoute: typeof AdminSeoPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners/new': {
      id: '/admin/partners/new'
      path: '/partners/new'
      fullPath: '/admin/partners/new'
      preLoaderRoute: typeof AdminPartnersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/create': {
      id: '/admin/orders/create'
      path: '/orders/create'
      fullPath: '/admin/orders/create'
      preLoaderRoute: typeof AdminOrdersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engineers/new': {
      id: '/admin/engineers/new'
      path: '/engineers/new'
      fullPath: '/admin/engineers/new'
      preLoaderRoute: typeof AdminEngineersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo/quick/products': {
      id: '/admin/seo/quick/products'
      path: '/seo/quick/products'
      fullPath: '/admin/seo/quick/products'
      preLoaderRoute: typeof AdminSeoQuickProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo/quick/manufacturers': {
      id: '/admin/seo/quick/manufacturers'
      path: '/seo/quick/manufacturers'
      fullPath: '/admin/seo/quick/manufacturers'
      preLoaderRoute: typeof AdminSeoQuickManufacturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo/quick/categories': {
      id: '/admin/seo/quick/categories'
      path: '/seo/quick/categories'
      fullPath: '/admin/seo/quick/categories'
      preLoaderRoute: typeof AdminSeoQuickCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo/quick/brands': {
      id: '/admin/seo/quick/brands'
      path: '/seo/quick/brands'
      fullPath: '/admin/seo/quick/brands'
      preLoaderRoute: typeof AdminSeoQuickBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$pageId/edit': {
      id: '/admin/pages/$pageId/edit'
      path: '/pages/$pageId/edit'
      fullPath: '/admin/pages/$pageId/edit'
      preLoaderRoute: typeof AdminPagesPageIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminBulkPricingRoute: typeof AdminBulkPricingRoute
  AdminCallbacksRoute: typeof AdminCallbacksRoute
  AdminCapacitiesRoute: typeof AdminCapacitiesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDeliveryTimeRoute: typeof AdminDeliveryTimeRoute
  AdminFuelsRoute: typeof AdminFuelsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminManufacturersRoute: typeof AdminManufacturersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEngineersNewRoute: typeof AdminEngineersNewRoute
  AdminOrdersCreateRoute: typeof AdminOrdersCreateRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminPartnersNewRoute: typeof AdminPartnersNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminSeoPagesRoute: typeof AdminSeoPagesRoute
  AdminEngineersIndexRoute: typeof AdminEngineersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPartnersIndexRoute: typeof AdminPartnersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminPagesPageIdEditRoute: typeof AdminPagesPageIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
  AdminSeoQuickBrandsRoute: typeof AdminSeoQuickBrandsRoute
  AdminSeoQuickCategoriesRoute: typeof AdminSeoQuickCategoriesRoute
  AdminSeoQuickManufacturersRoute: typeof AdminSeoQuickManufacturersRoute
  AdminSeoQuickProductsRoute: typeof AdminSeoQuickProductsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminBulkPricingRoute: AdminBulkPricingRoute,
  AdminCallbacksRoute: AdminCallbacksRoute,
  AdminCapacitiesRoute: AdminCapacitiesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDeliveryTimeRoute: AdminDeliveryTimeRoute,
  AdminFuelsRoute: AdminFuelsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminManufacturersRoute: AdminManufacturersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEngineersNewRoute: AdminEngineersNewRoute,
  AdminOrdersCreateRoute: AdminOrdersCreateRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminPartnersNewRoute: AdminPartnersNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminSeoPagesRoute: AdminSeoPagesRoute,
  AdminEngineersIndexRoute: AdminEngineersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPartnersIndexRoute: AdminPartnersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminPagesPageIdEditRoute: AdminPagesPageIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  AdminSeoQuickBrandsRoute: AdminSeoQuickBrandsRoute,
  AdminSeoQuickCategoriesRoute: AdminSeoQuickCategoriesRoute,
  AdminSeoQuickManufacturersRoute: AdminSeoQuickManufacturersRoute,
  AdminSeoQuickProductsRoute: AdminSeoQuickProductsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnerRouteChildren {
  PartnerEngineersRoute: typeof PartnerEngineersRoute
  PartnerOrdersRoute: typeof PartnerOrdersRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerEngineersRoute: PartnerEngineersRoute,
  PartnerOrdersRoute: PartnerOrdersRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PartnerRoute: PartnerRouteWithChildren,
  VehicleFinderRoute: VehicleFinderRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PSlugRoute: PSlugRoute,
  ProductsIdRoute: ProductsIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ManufacturersCategorySlugMakeSlugRoute:
    ManufacturersCategorySlugMakeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
